= Start react with redux 

:hp-tags: notes react


=== to be done

* redux dev tool

* react router (3 kinds of history, normally browserHistory)

* redux router (bind react router)

* https://github.com/rackt/redux/blob/master/docs/api/compose.md[redux `compose` utility function], from right to left = from bottom to top

* socket.io for test api connection

* bootstrap react

[source,javascript]
----- 
var button = ReactBootstrap.Button({
  bsStyle: "success",
  bsSize: "large",
  children: "Register"
});

React.render(button, mountNode);
-----


* `webpack-isomorphic-tools`, translate require function to hased real path on server side.

* the letter `isomorphic` means `universal`, which in web development means use same javascript code both for client side and server side.

* http://www.2ality.com/2015/04/webpack-es6.html[Writing client-side ES6 with webpack]

* multireducer: for which you can use the same reducer for different data model which has the same action types 

* scss just a compatible sass style, whereas sass add a 5 to 6 new syntax to css, `css-loader` is used here.

* `karma` used for watch the server, `mocha` used for create describe and it framework, `chai` used for test the syntax